spring.application.name=origem

# PostgreSQL Supabase Configuration
spring.datasource.url=jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.golbqunsexntrcqfgooe
spring.datasource.password=ZEYubFW$9KbXc7c
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# HikariCP Connection Pool (para suportar concorrência real)
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
